import { createStore } from "vuex";

export default createStore({
  state: {
    players: [
      {
        id: 1,
        name: "Eliza",
        emoticon: "😀",
        chair_number: 1,
        role: "Fascist",
        identity: "Hitler",
        chancellor: false,
        president: false,
        chancellor_candidate: false,
        president_candidate: false,
        alive: true,
      },
      {
        id: 2,
        name: "Umit",
        emoticon: "🧕🏽",
        chair_number: 2,
        role: "Democrat",
        identity: "Citizen",
        chancellor: false,
        president: false,
        chancellor_candidate: false,
        president_candidate: false,
        alive: true,
      },
      {
        id: 3,
        name: "Stefan",
        emoticon: "🤖",
        chair_number: 3,
        role: "Democrat",
        identity: "Citizen",
        chancellor: true,
        president: false,
        chancellor_candidate: false,
        president_candidate: false,
        alive: true,
      },
      {
        id: 4,
        name: "Stan",
        emoticon: "🤖",
        chair_number: 4,
        role: "Democrat",
        identity: "Citizen",
        chancellor: false,
        president: true,
        chancellor_candidate: false,
        president_candidate: false,
        alive: true,
      },
      {
        id: 5,
        name: "Nino",
        emoticon: "😍",
        chair_number: 5,
        role: "Democrat",
        identity: "Citizen",
        chancellor: true,
        president: false,
        chancellor_candidate: false,
        president_candidate: false,
        alive: true,
      },
      {
        id: 6,
        name: "Tirza",
        emoticon: "🤖",
        chair_number: 6,
        role: "Fascist",
        identity: "Citizen",
        chancellor: false,
        president: false,
        chancellor_candidate: true,
        president_candidate: false,
        alive: true,
      },
      {
        id: 7,
        name: "Anna",
        emoticon: "🧑🏼‍🎤",
        chair_number: 7,
        role: "Democrat",
        identity: "Citizen",
        chancellor: false,
        president: false,
        chancellor_candidate: false,
        president_candidate: true,
        alive: true,
      },
    ],
  },
  mutations: {},
  actions: {
    // ...
  },
  modules: {
    // ...
  },
});
